### PR TITLE
Introduce basic message-related messages

### PR DESCRIPTION
**Pull request by vasilvv**
[Review on Reviewable](https://reviewable.io/reviews/type-r/type-r-proto/1)

### CODE REVIEW

**Comment by achernya** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[common.proto, line 18 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2CIbvWxgvimQID5Q)** ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L18)):</sup>
Why not use google/protobuf/timestamp.proto?

---

<sup>**[common.proto, line 32 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2UpWzOetv3HPP_f2)** ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L32)):</sup>
Do we expect body to contain non-UTF-8 text?

---

<sup>**[common.proto, line 42 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2aLKD3P71KT5t3qB)** ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L42)):</sup>
Do sortpaths have to be printable? Replacing / with \0 may make it easier for us to do certain things, since a null will never appear otherwise. How do you intend to deal with escaping %, of / -> %?

---

<sup>**[common.proto, line 70 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2rZY6z9iEjO_kDfx)** ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L70)):</sup>
Why not take codes/status from https://github.com/google/googleapis/tree/master/google/rpc and use that? They're fairly rich.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/type-r/type-r-proto/1)

**Comment by vasilvv** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[common.proto, line 18 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2CIbvWxgvimQID5Q)** ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L18)):</sup>
Done.  I'm still confused by why I have to address those explicitly when the docs clearly use them without NS prefix, or why do I have to import them.  But that is something I will figure out another day.

---

<sup>**[common.proto, line 32 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2UpWzOetv3HPP_f2)** ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L32)):</sup>
Yeah, I imagine some protocols might send weird stuff, like images, or binary annotated text, or whatever.

---

<sup>**[common.proto, line 42 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2aLKD3P71KT5t3qB)** ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L42)):</sup>
I do want them to be printable and (in pessimistic case) typable.  They don't necessarily have to be reversibly unescapable, but it's probably the case that if we make them collide, we might regret that in the future.  I'll need to think more about this.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/type-r/type-r-proto/1)

**Comment by achernya** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[common.proto, line 14 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2CIbvWxgvimQID5Q)** ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L14)):</sup>
I believe that protobuf names follow the same rules as C++ namespaces. The examples likely were in the same package.

---

<sup>**[common.proto, line 27 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2UpWzOetv3HPP_f2)** ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L27)):</sup>
Please add that to the comment.

---

<sup>**[common.proto, line 37 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2aLKD3P71KT5t3qB)** ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L37)):</sup>
Let's at least start by escaping / to //. (or switch to using \ and \ since // looks a bit weird)

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/type-r/type-r-proto/1)

**Comment by vasilvv** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

_[common.proto, line 32 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2UpWzOetv3HPP_f2:-KCYL2x1iLiLp23MrkqZ:-499146009) ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L32)):_
Done.

---

_[common.proto, line 42 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2aLKD3P71KT5t3qB:-KCYKaje9AvJE1RFfmT6:-499146009) ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L42)):_
Done.

---

_[common.proto, line 70 [r1]](https://reviewable.io:443/reviews/type-r/type-r-proto/1#-JzJ2rZY6z9iEjO_kDfx:-KCYJvMcYoIPz-dIVBrp:-499146009) ([raw file](https://github.com/type-r/type-r-proto/blob/6013954acd323ac1be98f4a7647ab4ddea5dcd6a/common.proto#L70)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/type-r/type-r-proto/1)_

**Comment by achernya** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/type-r/type-r-proto/1)_

**Pull request closed without merging**
